### ISSUE TITLE
prefixed commands and other things on the TODO list

### ISSUE THREAD

**Issue by NikkyAI** [elytra/MatterLink#1]
we need commands that can be executed from the bridge using a configurable prefix

example: `!players`

later we want to register more commands and configure whhere/who cna invoke them
(bridged-chat, ingame-chat, ingame-ops & server)

maybe add a mapping in the config for easily addding custom commands

example: 

structure
```yaml
info:
  text: get the the client here.. (insert url) and connect to (insert server url)
  permission: [bridge, chat, op]
  targets: [bridge, chat] # possibly console too
  consume_invocation: true # do not send the invocation command to the mc server (or the other way around)
```

other possibilities include.. replacing text in the `text` variable, eg `{{PLAYERNAME}}`

mapping different responses (as differend strings can be replaced in different context)
example:
```yaml
bacon:
  response:
    bridge: "spam spam spam spam"
    chat: "spammedy spaaaaam"
    console: "and eggs - {{COMMAND_SENDER}}"
```

iuf we find a usable string templating engine that can do loops and similar things too we cna implement playerlist and other features completly config driven too.. until then we hardcode things
